# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f07ac680220eb4e061e35f5d1af9c1a80969dcaee1d20826de91c52e2e3e2b697c2f9eabaf91e74765ce24f9bfb08ec9080a2c42eff50f44cf0ecc3124eb3f72

test:
  secret_key_base: 7cba24e0a8a6898353b1547e3cde4e4b68a6ec80002a23e1b9445fd6474f8fcb5e1edb261687f6da0a982f0f2cbe803bf381dc2a6ad6b04aac2280d338a42d32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
